name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: Devops first job
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: List and Read files
        run: 
              echo "Welcome to the CI/CD world GitHub Actions"
              ls -la
              cat happy.txt
              cat dockerfile
