name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: My updated job
    runs-on: ubuntu-latest
    steps:
      - name: Updated Welcome Message
        run: echo "Welcome to the CI/CD world GitHub Actions"

      - name: List all Files including hidden 
        run: ls -a

      - name: Display current working directory 
        run: pwd
